import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./shared/context/AuthProvider";
import SocketProvider from "./shared/context/SocketProvider";
import ConfirmProvider from "./shared/context/ConfirmProvider";
import { PresenceProvider } from "./shared/context/PresenceProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SocketProvider>
            <PresenceProvider>
              <ConfirmProvider>{children}</ConfirmProvider>
            </PresenceProvider>
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
