// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let dbUrl: string | undefined = process.env.SUPABASE_DB_URL;
if (!dbUrl) {
  throw new Error(
    "DATABASE_URL environment variable is not set. Please set it to your database connection string."
  );
}


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
